name: eCAL Integration Tests

on:
  repository_dispatch:
    types: [run-tests]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  run-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Pull existing gh-pages branch into folder
      run: |
        git clone --branch gh-pages https://github.com/${{ github.repository }} gh-pages || mkdir gh-pages

    - name: Create Timestamped Reports Folder
      run: |
        echo "REPORT_TS=$(date +'%Y-%m-%d_%H-%M-%S')" >> $GITHUB_ENV 

    - name: Set up Docker
      uses: docker/setup-buildx-action@v3

    - name: Build ecal_base Image
      run: |
        docker build -t ecal_base -f integration_tests/docker/Dockerfile.ecal_base .
    
    - name: Install Robot Framework + Docker SDK
      run: |
        python3 -m pip install --upgrade pip
        pip install robotframework docker

    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=$PWD/integration_tests/lib" >> $GITHUB_ENV

    # Test 1: basic_pub_sub
    - name: Run Test basic_pub_sub
      run: |
        cd integration_tests/basic_pub_sub
        robot robottests/basic_pub_sub.robot || echo "Test failed"

    # Test 2: message_validation
    - name: Run Test message_validation
      run: |
        cd integration_tests/message_validation
        robot robottests/message_validation.robot || echo "Test failed"

    # Test 3: multi_pub_sub
    - name: Run Test multi_pub_sub
      run: |
        cd integration_tests/multi_pub_sub
        robot robottests/multi_pub_sub.robot || echo "Test failed"

    # Test 4: network_crash
    - name: Run Test network_crash
      run: |
        cd integration_tests/network_crash
        robot robottests/network_crash.robot || echo "Test failed"

    # Test 5: pub_crash
    - name: Run Test pub_crash
      run: |
        cd integration_tests/pub_crash
        robot robottests/pub_crash.robot || echo "Test failed"

    # Test 6: sub_crash
    - name: Run Test sub_crash
      run: |
        cd integration_tests/sub_crash
        robot robottests/sub_crash.robot || echo "Test failed"

    # Test 7: sub_send_crash
    - name: Run Test sub_send_crash
      run: |
        cd integration_tests/sub_send_crash
        robot robottests/sub_send_crash.robot || echo "Test failed"

    - name: Archive all Robot logs (for manual download only)
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: robot-reports
        path: |
          integration_tests/**/log.html
          integration_tests/**/output.xml
          integration_tests/**/report.html

    - name: Copy only valid Robot Reports to gh-pages folder
      if: always()
      run: |
        mkdir -p gh-pages/${REPORT_TS}
        for dir in integration_tests/*; do
          if [[ -f "$dir/log.html" || -f "$dir/report.html" || -f "$dir/output.xml" ]]; then
            test_name=$(basename $dir)
            mkdir -p gh-pages/${REPORT_TS}/${test_name}
            cp $dir/log.html gh-pages/${REPORT_TS}/${test_name}/ || true
            cp $dir/report.html gh-pages/${REPORT_TS}/${test_name}/ || true
            cp $dir/output.xml gh-pages/${REPORT_TS}/${test_name}/ || true
          fi
        done

    - name: Generate index.html with Dropdowns
      if: always()
      run: |
        INDEX_FILE=gh-pages/index.html
        echo "<!DOCTYPE html>" > $INDEX_FILE
        echo "<html lang='en'><head><meta charset='UTF-8'>" >> $INDEX_FILE
        echo "<title>eCAL Test Reports</title>" >> $INDEX_FILE
        echo "<style>" >> $INDEX_FILE
        echo "body { font-family: Arial, sans-serif; padding: 2em; background: #f9f9f9; }" >> $INDEX_FILE
        echo "h1 { color: #333; }" >> $INDEX_FILE
        echo "details { background: #fff; border: 1px solid #ccc; margin-bottom: 10px; padding: 10px; border-radius: 4px; }" >> $INDEX_FILE
        echo "summary { font-weight: bold; font-size: 1.1em; cursor: pointer; }" >> $INDEX_FILE
        echo "ul { list-style-type: none; padding-left: 1em; }" >> $INDEX_FILE
        echo "li { margin: 6px 0; }" >> $INDEX_FILE
        echo "a { text-decoration: none; color: #0366d6; }" >> $INDEX_FILE
        echo "a:hover { text-decoration: underline; }" >> $INDEX_FILE
        echo "</style></head><body>" >> $INDEX_FILE
        echo "<h1>eCAL Integration Test Reports</h1>" >> $INDEX_FILE

        for folder in $(ls -1 gh-pages | grep -E '^[0-9]{4}-' | sort -r); do
          echo "<details>" >> $INDEX_FILE
          echo "<summary>Test Run: ${folder}</summary>" >> $INDEX_FILE
          echo "<ul>" >> $INDEX_FILE
          for test in $(ls -1 gh-pages/$folder); do
            if [[ -f "gh-pages/$folder/$test/log.html" || -f "gh-pages/$folder/$test/report.html" || -f "gh-pages/$folder/$test/output.xml" ]]; then
              echo "<li><b>${test}</b>: " >> $INDEX_FILE
              [[ -f "gh-pages/$folder/$test/log.html" ]] && echo "<a href='${folder}/${test}/log.html'>log</a> | " >> $INDEX_FILE
              [[ -f "gh-pages/$folder/$test/report.html" ]] && echo "<a href='${folder}/${test}/report.html'>report</a> | " >> $INDEX_FILE
              [[ -f "gh-pages/$folder/$test/output.xml" ]] && echo "<a href='${folder}/${test}/output.xml'>xml</a>" >> $INDEX_FILE
              echo "</li>" >> $INDEX_FILE
            fi
          done
          echo "</ul></details>" >> $INDEX_FILE
        done

        echo "</body></html>" >> $INDEX_FILE

    - name: Deploy to GitHub Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./gh-pages
        publish_branch: gh-pages
        commit_message: "Deploy test report at ${{ env.REPORT_TS }}"
        allow_empty_commit: true
        keep_files: true