name: Trigger GitHub Pages Deployment

on:
  push:
    branches:
      - gh-pages
  workflow_dispatch:
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger GitHub Pages Deployment
      uses: actions/deploy-pages@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
